name: Build and Push to ECR

on:
  push:
    branches:
      - main
      - staging
    tags:
      - 'v*.*.*'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Determine environment and fetch credentials from SSM
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            ENV=staging
            TAG=staging
          elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
            ENV=prod
            TAG="${GITHUB_REF#refs/tags/}"
          else
            ENV=prod
            TAG=latest
          fi

          echo "tag=$TAG" >> $GITHUB_ENV
          echo "env=$ENV" >> $GITHUB_ENV

          DB_URL=$(aws ssm get-parameter --name "/q3/$ENV/DB_URL" --with-decryption --query "Parameter.Value" --output text)
          SECRET_KEY_BASE=$(aws ssm get-parameter --name "/q3/$ENV/SECRET_KEY_BASE" --with-decryption --query "Parameter.Value" --output text)

          echo "DB_URL=$DB_URL" >> $GITHUB_ENV
          echo "SECRET_KEY_BASE=$SECRET_KEY_BASE" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY }}:${{ env.tag }} .

      - name: Tag image for ECR
        run: |
          docker tag ${{ secrets.ECR_REPOSITORY }}:${{ env.tag }} \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:${{ env.tag }}

      - name: Push to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:${{ env.tag }}
